service: hello-nuxt3

frameworkVersion: '>=2'

plugins:
  - serverless-apigw-binary
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, self:custom.defaultStage}
  stackName: ${self:service}-${self:provider.stage}

custom:
  defaultStage: dev
  apigwBinary:
    types:
      - '*/*'
  s3Sync:
    - bucketNameKey: AssetsBucketName
      localDir: app/public
      deleteRemoved: false
    - bucketNameKey: AssetsBucketName
      localDir: .output/public/_nuxt
      bucketPrefix: _nuxt/
      deleteRemoved: false

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Join:
            - ""
            - - ${self:service}
              - "-"
              - ${self:provider.stage}
              - "-"
              - !Ref ApiGatewayRestApi
  Outputs:
    AssetsBucketName:
      Value: !Ref AssetsBucket
    ApiGatewayRestApi:
      Value: !Ref ApiGatewayRestApi

package:
  exclude:
    - node_modules/**
    - .nuxt/**
    - app/**
    - .components.gen.js
    - .idea/**
  include:
    - .output
    - serverless

functions:
  handler:
    handler: serverless/apigw.handler
    environment:
      STAGE: ${self:provider.stage}
      NODE_ENV: production
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: get
